In [2]:
import pandas as pd

In [1]:
!ls

'unichem_master_ids[0-10000].csv'	 'unichem_master_ids[80001-160000].csv'
'unichem_master_ids[10001-20000].csv'	  unichem_master_ids.csv
'unichem_master_ids[160001-500000].csv'  'Unify unichem files.ipynb'
'unichem_master_ids[20001-80000].csv'

In [3]:
a = pd.read_csv("unichem_master_ids[0-10000].csv")
b = pd.read_csv("unichem_master_ids[10001-20000].csv")
columns = a.columns

In [4]:
unichem = pd.concat([a, b])
unichem

,uci,chembl,drugbank,pdb,gtopdb,pubchem_dotf,kegg_ligand,chebi,nih_ncc,zinc,...,metabolights,brenda,rhea,chemicalbook,swisslipids,dailymed,clinicaltrials,rxnorm,MedChemExpress,probes_and_drugs
0,1,CHEMBL172985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028009973,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,CHEMBL254982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000101162868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,CHEMBL1078329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000049802730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,CHEMBL518270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000040918656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,CHEMBL302512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000026293328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,19995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9995,19996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,19997,CHEMBL362462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028104124,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,19998,CHEMBL292519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000095609667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,19999,CHEMBL188901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000013648427,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
b = pd.read_csv("unichem_master_ids[80001-160000].csv")
unichem = pd.concat([unichem, b])

In [10]:
unichem

,uci,chembl,drugbank,pdb,gtopdb,pubchem_dotf,kegg_ligand,chebi,nih_ncc,zinc,...,metabolights,brenda,rhea,chemicalbook,swisslipids,dailymed,clinicaltrials,rxnorm,MedChemExpress,probes_and_drugs
0,1,CHEMBL172985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028009973,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,CHEMBL254982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000101162868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,CHEMBL1078329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000049802730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,CHEMBL518270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000040918656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,CHEMBL302512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000026293328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79993,159995,CHEMBL230972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028711417,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PD093418
79994,159996,CHEMBL190913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000013646537,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79995,159997,CHEMBL377724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79996,159998,CHEMBL569061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000045254443,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79997,159999,CHEMBL552491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
unichem.to_csv('unichem_master_ids.csv', index=False)

In [37]:
unichem = pd.read_csv("unichem_master_ids.csv")
unichem

,uci,chembl,drugbank,pdb,gtopdb,pubchem_dotf,kegg_ligand,chebi,nih_ncc,zinc,...,metabolights,brenda,rhea,chemicalbook,swisslipids,dailymed,clinicaltrials,rxnorm,MedChemExpress,probes_and_drugs
0,1,CHEMBL172985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028009973,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,CHEMBL254982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000101162868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,CHEMBL1078329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000049802730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,CHEMBL518270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000040918656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,CHEMBL302512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000026293328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159986,159995,CHEMBL230972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028711417,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PD093418
159987,159996,CHEMBL190913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000013646537,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159988,159997,CHEMBL377724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159989,159998,CHEMBL569061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000045254443,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159990,159999,CHEMBL552491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
unichem[unichem['uci'] == 10000]

Empty DataFrame
Columns: [uci, chembl, drugbank, pdb, gtopdb, pubchem_dotf, kegg_ligand, chebi, nih_ncc, zinc, emolecules, atlas, fdasrs, surechembl, pharmgkb, hmdb, selleck, pubchem_tpharma, pubchem, mcule, nmrshiftdb2, lincs, actor, recon, molport, nikkaji, bindingdb, comptox, lipidmaps, drugcentral, carotenoiddb, metabolights, brenda, rhea, chemicalbook, swisslipids, dailymed, clinicaltrials, rxnorm, MedChemExpress, probes_and_drugs]
Index: []

[0 rows x 41 columns]

In [39]:
for i in range(1, 160000):
    if (unichem['uci'] == i).sum() != 1:
        print(i)

10000
20000
33869
55513
55514
55515
80000
124764

In [40]:
missing_ids = pd.read_csv("unichem_master_missing_ids.csv")
missing_ids

,uci,chembl,drugbank,pdb,gtopdb,pubchem_dotf,kegg_ligand,chebi,nih_ncc,zinc,...,metabolights,brenda,rhea,chemicalbook,swisslipids,dailymed,clinicaltrials,rxnorm,MedChemExpress,probes_and_drugs
0,10000,CHEMBL269863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000029136123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20000,CHEMBL175986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000013607054,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,33869,CHEMBL473615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000035950946,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,55513,CHEMBL74618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,55514,CHEMBL291305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000013863044,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,55515,CHEMBL1078562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000049771291,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,80000,CHEMBL437003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028710808,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,124764,CHEMBL413274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
unichem

,uci,chembl,drugbank,pdb,gtopdb,pubchem_dotf,kegg_ligand,chebi,nih_ncc,zinc,...,metabolights,brenda,rhea,chemicalbook,swisslipids,dailymed,clinicaltrials,rxnorm,MedChemExpress,probes_and_drugs
0,1,CHEMBL172985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028009973,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,CHEMBL254982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000101162868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,CHEMBL1078329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000049802730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,CHEMBL518270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000040918656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,CHEMBL302512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000026293328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159986,159995,CHEMBL230972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028711417,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PD093418
159987,159996,CHEMBL190913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000013646537,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159988,159997,CHEMBL377724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159989,159998,CHEMBL569061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000045254443,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159990,159999,CHEMBL552491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
unichem = pd.concat([unichem, missing_ids])
unichem.sort_values('uci')

,uci,chembl,drugbank,pdb,gtopdb,pubchem_dotf,kegg_ligand,chebi,nih_ncc,zinc,...,metabolights,brenda,rhea,chemicalbook,swisslipids,dailymed,clinicaltrials,rxnorm,MedChemExpress,probes_and_drugs
0,1,CHEMBL172985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028009973,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,CHEMBL254982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000101162868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,CHEMBL1078329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000049802730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,CHEMBL518270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000040918656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,CHEMBL302512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000026293328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159986,159995,CHEMBL230972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028711417,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PD093418
159987,159996,CHEMBL190913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000013646537,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159988,159997,CHEMBL377724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159989,159998,CHEMBL569061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000045254443,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159990,159999,CHEMBL552491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
unichem.to_csv('unichem_master_ids.csv', index=False)

In [45]:
unichem = pd.read_csv("unichem_master_ids.csv")
unichem

,uci,chembl,drugbank,pdb,gtopdb,pubchem_dotf,kegg_ligand,chebi,nih_ncc,zinc,...,metabolights,brenda,rhea,chemicalbook,swisslipids,dailymed,clinicaltrials,rxnorm,MedChemExpress,probes_and_drugs
0,1,CHEMBL172985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028009973,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,CHEMBL254982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000101162868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,CHEMBL1078329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000049802730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,CHEMBL518270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000040918656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,CHEMBL302512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000026293328,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159994,55513,CHEMBL74618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159995,55514,CHEMBL291305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000013863044,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159996,55515,CHEMBL1078562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000049771291,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159997,80000,CHEMBL437003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000028710808,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159998,124764,CHEMBL413274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
b = pd.read_csv("unichem_master_ids[160001-].csv")
b

,uci,chembl,drugbank,pdb,gtopdb,pubchem_dotf,kegg_ligand,chebi,nih_ncc,zinc,...,metabolights,brenda,rhea,chemicalbook,swisslipids,dailymed,clinicaltrials,rxnorm,MedChemExpress,probes_and_drugs
0,160001,CHEMBL506952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000253951534,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,160002,CHEMBL453935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000006593235,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,160003,CHEMBL601994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000000055891,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,160004,CHEMBL356146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000013760587,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,160005,CHEMBL584608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000045319052,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8383,168385,CHEMBL1171152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000001857622,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8384,168386,CHEMBL303618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000026280850,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8385,168387,CHEMBL174397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000034803471,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8386,168388,CHEMBL150452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8387,168389,CHEMBL533775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZINC000045188210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN